// src/utils/moduleTasksInitializers.ts
import type { Task } from '@/models/models'

export function getInitialTasksForModule(moduleId: number): Task[] {
  switch (moduleId) {
    case 1: // Existencia
      return [
        {
          id: 1,
          taskCode: 'A',
          procedureDescription: 'Realizar inventario Selectivo a una muestra de Sku',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 101,
              requerimentCode: 1,
              procedureDescription:
                'Tomar una muestra sobre la línea que presento mayor diferencia en Inventario General, verificar si están cuadrados los sku´s, evaluar según escala determinada (perdida sobre % que representa el costo de la venta, no debería sobrepasar 1%)',
              riskLevel: 'Muy Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              visualAid: 'Debe utilizar planilla Excel "Planilla para Conteo", para realizar el scan de los SKU´s involucrados, en esta planilla se debe pegar el stock teórico de los Sku´s seleccionados para la muestra de auditoría, de debe revisar que las fórmulas estén actualizadas y se procede al conteo físico en Sala, Bodega o trastienda, también se debe considerar los productos en estado de segunda a los cuales no tengan el traspaso de almacén correspondiente, lo mismo debe ser considerado para los productos en estado de merma que no han sido procesados.',
              observations: [],
            },
            {
              id: 102,
              requerimentCode: 2,
              procedureDescription:
                'Se debe realizar inspección visual de todos los espacios de la tienda, si se detecta productos en zonas no permitidas, esto debe afectar negativamente a la puntuación',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 2,
          taskCode: 'B',
          procedureDescription: 'Mermas',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'Identificar el espacio físico asignado para el almacenamiento de la Merma',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              visualAid: 'Verificar que la merma almacenada esté informada a Control de Existencia. Esto se revisar en libro de registro de mermas, si la merma física ya fue informada y no ha sido destruida, esto afecta negativamente a la tienda (Tienda deberá tener levantada la ficha de calidad y el correo de respaldo en caso que sea merma de calidad). Y se deberá levantar al área comercial, posterior a la revisión de auditoría, para gestión de los productos en espera si no se ha dado respuesta a la tienda.',
              observations: [],
            },
            {
              id: 202,
              requerimentCode: 2,
              procedureDescription:
                'Revisar en el panel web de control de existencias que se esté registrando la merma operacional, calidad y E-Commerce, y que los respaldos estén anexados en cada registro',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              visualAid: 'En el panel web (Easy Store) ingresar  identificar la tienda a auditar, ingresar a la opción mermas, seleccionar el período por auditar (3 semanas), y revisar que se estén registrando las mermas y que cuenten con el respaldo fotográfico y documental',
              observations: [],
            },
            {
              id: 203,
              requerimentCode: 3,
              procedureDescription: 'Revisar almacén destinado para la segunda selección en tienda',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              visualAid: 'Si la tienda cuenta con stock sistémico (para el almacén 0092) se debe seleccionar una muestra y revisar que se cumplan los criterios definidos en la PPT sobre Disposición de Mermas y Segunda Selección. Día jueves debería enviarse correo de traspaso (manual) a zonal correspondiente.',
              observations: [],
            },
          ],
        },
        {
          id: 3,
          taskCode: 'C',
          procedureDescription: 'Revision en el monitor WEB de Existencias',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 301,
              requerimentCode: 1,
              procedureDescription:
                'Recepción de Camión: Se debe revisar que no existan entregas abiertas y todas deben estar contabilizadas con su respectivo documento SAP de contabilización',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 302,
              requerimentCode: 2,
              procedureDescription:
                'Mermas: Se debe revisar que estén registradas las mermas con su respectivo respaldo (Foto, correo con la autorización para las mermas de calidad, Nota de Crédito para las Mermas ecommerce)',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 303,
              requerimentCode: 3,
              procedureDescription:
                'Inventarios Selectivos: Revisar que los inventarios selectivos estén registrados y contabilizados',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 304,
              requerimentCode: 4,
              procedureDescription:
                'Traslados, Retiros y Cambios de Almacén: Revisar que los traslados, Retiros y cambios de almacén estén correctamente registrados',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 4,
          taskCode: 'D',
          procedureDescription: 'Productos para la venta',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 401,
              requerimentCode: 1,
              procedureDescription:
                'Existen productos de venta en uso en el Back office/ trastienda',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 402,
              requerimentCode: 2,
              procedureDescription:
                'Verificar que las bodegas se encuentran ordenadas y los productos bien almacenados',
              riskLevel: 'Medio',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 5,
          taskCode: 'E',
          procedureDescription: 'Seguimiento Visita Anterior',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 501,
              requerimentCode: 1,
              procedureDescription:
                'Cuando aplique, valide si se repiten las mismas observaciones que la auditoría anterior',
              riskLevel: 'Muy Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
      ]
    case 2: // Administracion
      return [
        {
          id: 1,
          taskCode: 'A',
          procedureDescription: 'Fiscalizacion',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 101,
              requerimentCode: 1,
              procedureDescription:
                'Patente comercial se encuentra vigente y a la vista de los clientes',
              riskLevel: 'Muy Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 102,
              requerimentCode: 2,
              procedureDescription:
                'El Jefe de Tienda y Encargado de Zona sabe dónde se encuentra la declaración de IVA de los meses anteriores',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 2,
          taskCode: 'B',
          procedureDescription: 'Temas Varios',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'Los colaboradores conocen los procedimientos o instructivos que rigen la forma de operar de la tienda',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 202,
              requerimentCode: 2,
              procedureDescription:
                'El libro de sugerencias, Felicitaciones y reclamos cumple con las normas y requisitos establecidos',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 2,
          taskCode: 'C',
          procedureDescription: 'Seguimiento Visita Anterior',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'Cuando aplique, valide si se repiten las mismas observaciones que la auditoría anterior',
              riskLevel: 'Muy Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
      ]
    case 3: // TI Mantencion
      return [
        {
          id: 1,
          taskCode: 'A',
          procedureDescription: 'Mantencion',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 101,
              requerimentCode: 1,
              procedureDescription:
                '¿Se encuentran los centros eléctricos de las cajas en buen estado y anclados al mueble?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 102,
              requerimentCode: 2,
              procedureDescription: 'El piso y cobrejuntas se encuentran en buen estado?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 103,
              requerimentCode: 3,
              procedureDescription: '¿El techo se encuentra en buen estado?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 104,
              requerimentCode: 4,
              procedureDescription: 'Aire acondicionado se encuentra operativo y en buen estado',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 2,
          taskCode: 'B',
          procedureDescription: 'TI',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'La Sala Técnica/Electricidad se encuentra despejada (sin producto, cajas o artículo que no corresponda)',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 202,
              requerimentCode: 2,
              procedureDescription:
                'Se encuentra la UPS en el rack de comunicaciones funcionando y con los servidores conectados al mismo',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 203,
              requerimentCode: 3,
              procedureDescription:
                'Los Pinpad de contingencia están activos y con carga? Además ¿Se encuentran los cargadores de pinpad bien distribuidos para evitar alargadores?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 204,
              requerimentCode: 4,
              procedureDescription:
                '¿Los POS se encuentran todos operativos y en buen estado? Además ¿Se Encuentra el lineal de cajas bajo el POS despejado y sin artículos que puedan generar peligro a nivel eléctrico (Agua, papeles, alcohol, etc)?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 205,
              requerimentCode: 5,
              procedureDescription:
                'Tiene todos sus Tablets, impresoras, scanner, funcionando y en buen estado',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 3,
          taskCode: 'C',
          procedureDescription: 'Seguimiento Visita Anterior',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'Cuando aplique, valide si se repiten las mismas   observaciones que la auditoría anterior',
              riskLevel: 'Muy Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
      ]
    case 4: // RR.HH - SSO
      return [
        {
          id: 1,
          taskCode: 'A',
          procedureDescription: 'RR.HH',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 101,
              requerimentCode: 1,
              procedureDescription:
                'Los documentos de los colaboradores se encuentran firmados en Buk (Contrato, Reglamento Interno, Anexos, etc.)',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              visualAid: 'Validar reporte extraido de Buk (documentos pendientes de firma) v/s lo que le muestra el jefe de tienda (debe mostrar documento firmado por el trabajador). Ciclo de vida envía correo dando estatus (al menos quincenal), por lo cual no se puede desconocer en tienda si existen pendientes de firma',
              observations: [],
            },
            {
              id: 102,
              requerimentCode: 2,
              procedureDescription:
                'Las Horas Extras se encuentran autorizadas por el Jefe Zonal a través de correo, además se cumple con la ley (máximo 2 HE diarias y 10 a la semana)',
              riskLevel: 'Muy Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              visualAid: 'Ingresar a Geovictoria y validar que los colaboradores que realizan horas extras cumplen con la ley, además verificar que estas HE fueron autorizadas a través de correo por el Jefe Zonal, revisar 4 semanas (colaboradores con jornada PT20C no pueden realizar horas extras).',
              observations: [],
            },
            {
              id: 103,
              requerimentCode: 3,
              procedureDescription:
                'Jefaturas saben dónde se encuentra Registro de Firma Electrónica para presentar ante la inspección del trabajo',
              riskLevel: 'Medio',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 104,
              requerimentCode: 4,
              procedureDescription: '¿Las mallas de turno están firmadas y publicadas?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 2,
          taskCode: 'B',
          procedureDescription: 'SSO',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'Los extintores están en sus respectivos calzos y con su mantención al día?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 202,
              requerimentCode: 2,
              procedureDescription:
                'Las señaléticas de seguridad de la tienda están puestas y en buen estado? Además ¿Se encuentran las salidas(s) de emergencia libres para su uso?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 203,
              requerimentCode: 3,
              procedureDescription:
                'Se encuentra Registro Capacitación de uso y manejo de escaleras, Recepción de Camión y Uso de Cuchillo Cartonero',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 204,
              requerimentCode: 4,
              procedureDescription:
                'Si la tienda cuenta con más de 25 trabajadores, verificar que esté constituido el Comité Paritario, además que se encuentren las actas de reuniones mensuales firmadas',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 205,
              requerimentCode: 6,
              procedureDescription:
                'Verificar que se encuentre el registro de Control de Plagas que se realiza de forma mensual',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 3,
          taskCode: 'C',
          procedureDescription: 'Seguimiento Visita Anterior',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'Cuando aplique, valide si se repiten las mismas observaciones que la auditoría anterior',
              riskLevel: 'Muy Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
      ]
    case 5: // Recaudacion
      return [
        {
          id: 1,
          taskCode: 'A',
          procedureDescription: 'Arqueo',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 101,
              requerimentCode: 1,
              procedureDescription:
                'Fondo de Sencillo cuadrado, ordenado y al interior de caja fuerte, en este ítem se debe abrir un recuadro en el cual se ingresa el desglose del fondo de sencillo asignado a la tienda',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              visualAid: 'Realizar un arqueo al o los Fondos de Sencillo que se encuentran en la tienda, tolerancia de desviación $500 (monto superior esta descuadrado), realizar una inspección visual del lugar en que se encuentra el dinero (si una caja aun no abre, la dotación debe estar en caja fuerte no en la gaveta).',
              observations: [],
            },
            {
              id: 102,
              requerimentCode: 2,
              procedureDescription:
                'Tienda realiza cuadratura del Fondo de Sencillo todos los días',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              visualAid: 'Revisar carpeta que se encuentra en Drive (Respaldo de Folio - Arqueo Sencillo) y validar si se realizaron las cuadraturas todos los días (revisar 20 dias), además analizar si existen variaciones muy grandes de billetes de $1000 y preguntar que paso (las tiendas tienen prohibido ir a cambiar dinero al banco o con una persona externa a menos que sea autorizado a través de correo por el Jefe Zonal). Importante: si la información se encuentra en una carpeta distinta a la creada por Folios,  el punto no cumple.',
              observations: [],
            },
            {
              id: 103,
              requerimentCode: 3,
              procedureDescription: 'Fondo de Sencillo del mes anterior depositado',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              visualAid: 'Verificar que el Fondo de Sencillo del mes anterior este depositado, validar en drive comprobante de recepción de valores y comprobante de depósito, revisar 4 meses hacia atrás (los comprobantes deben estar ordenados y resguardados en la carpeta del mes al que corresponden.  Importante: si la información se encuentra en una carpeta distinta a la creada por Folios, el punto no cumple.',
              observations: [],
            },
          ],
        },
        {
          id: 2,
          taskCode: 'B',
          procedureDescription: 'Folios',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'Los retiros y depósitos en Compusafe cumplen con lo estipulado en el Procedimiento de Procesos y Sistema de Caja',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              visualAid: 'Verificar a través del Folio o en la página de Brinks que los comprobantes de depósito no sean superior a $200.000, además revisar la hora en que se realizan estos depósitos por que en algunas ocasiones acumulan en caja más del dinero permitido, pero lo depositan en forma separada. se debe revisar dos semanas.',
              observations: [],
            },
            {
              id: 202,
              requerimentCode: 2,
              procedureDescription:
                'Notas de Pedido cumplen con el protocolo, además se ingresan diariamente las NC por egreso en el drive',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              visualAid: 'Revisar los talonarios de las notas de pedido que debería tener la tienda, verificar si se ha usado algún documento ( en este caso ver  si se encuentra respaldada en drive -planilla Notas de Pedido) si  existe un documento nulo este debe estar con todas sus copias . B.2.2 Validar que el comprobante de la NC física esté firmada por el cliente, por el jefe/encargado de zona (NC), y tener el documento de respaldo de la anulación (boleta completa si es anulación total o fotocopia si es parcial). El folio debe estar guardado al igual que en tocornal (Deben estar en sobres, por día/mes, con sus correspondientes comprobantes. Importante: si la información se encuentra en una carpeta distinta a la creada por Folios,  el punto no cumple. Adicionalmente si se tiene dudas respecto del proceso o no hay evidencia clara de firmas por parte de supervisor directo, se recomienda efectuar procedimiento de revisión de cámaras para corroborar.',
              observations: [],
            },
            {
              id: 203,
              requerimentCode: 3,
              procedureDescription:
                'Se encuentra cuadrado el cierre de turno (no considerar voucher de débito y crédito)',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              visualAid: 'Revisar el Folio o BO Central y validar que las cuadraturas de cierre de caja no presenten diferencias (no considerar voucher de debito y crédito), revisar 7 días. Si hay un faltante, validar que éste haya sido enviado. Debe ser enviado a más tardar el día siguiente am por correo (desde los 100 pesos). Inmediatamente debería firmar la hoja de autorización de descuento y enviarla a folio.',
              observations: [],
            },
            {
              id: 204,
              requerimentCode: 4,
              procedureDescription:
                '¿Las tarjetas de supervisor en tienda, se ajustan a protocolo vigente?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              visualAid: 'Identificar quienes tienen tarjeta de supervisor y validar a través de Bo Central que los días que estos colaboradores tuvieron día libre su tarjeta no se utilizó (validar tarjeta de 3 colaboradores).',
              observations: [],
            },
          ],
        },
        {
          id: 3,
          taskCode: 'C',
          procedureDescription: 'Seguimiento Visita Anterior',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'Cuando aplique, valide si se repiten las mismas observaciones que la auditoría anterior',
              riskLevel: 'Muy Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
      ]
    default:
      return []
  }
}
