// src/utils/moduleTasksInitializers.ts
import type { AuditModules, Task } from '@/models/models'

export function getInitialTasksForModule(moduleId: number): Task[] {
  switch (moduleId) {
    case 1: // Existencia
      return [
        {
          id: 1,
          taskCode: 'A',
          procedureDescription: 'Realizar inventario Selectivo a una muestra de Sku',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 101,
              requerimentCode: 1,
              procedureDescription:
                'Tomar una muestra sobre la línea que presento mayor diferencia en Inventario General, verificar si están cuadrados los sku´s, evaluar según escala determinada (perdida sobre % que representa el costo de la venta, no debería sobrepasar 1%)',
              riskLevel: 'Muy Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 102,
              requerimentCode: 2,
              procedureDescription:
                'Se debe realizar inspección visual de todos los espacios de la tienda, si se detecta productos en zonas no permitidas, esto debe afectar negativamente a la puntuación',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 2,
          taskCode: 'B',
          procedureDescription: 'Mermas',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'Identificar el espacio físico asignado para el almacenamiento de la Merma',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 202,
              requerimentCode: 2,
              procedureDescription:
                'Revisar en el panel web de control de existencias que se esté registrando la merma operacional, calidad y E-Commerce, y que los respaldos estén anexados en cada registro',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 203,
              requerimentCode: 3,
              procedureDescription: 'Revisar almacén destinado para la segunda selección en tienda',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 3,
          taskCode: 'C',
          procedureDescription: 'Revision en el monitor WEB de Existencias',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 301,
              requerimentCode: 1,
              procedureDescription:
                'Recepción de Camión: Se debe revisar que no existan entregas abiertas y todas deben estar contabilizadas con su respectivo documento SAP de contabilización',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 302,
              requerimentCode: 2,
              procedureDescription:
                'Mermas: Se debe revisar que estén registradas las mermas con su respectivo respaldo (Foto, correo con la autorización para las mermas de calidad, Nota de Crédito para las Mermas ecommerce)',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 303,
              requerimentCode: 3,
              procedureDescription:
                'Inventarios Selectivos: Revisar que los inventarios selectivos estén registrados y contabilizados',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 304,
              requerimentCode: 4,
              procedureDescription:
                'Traslados, Retiros y Cambios de Almacén: Revisar que los traslados, Retiros y cambios de almacén estén correctamente registrados',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 4,
          taskCode: 'D',
          procedureDescription: 'Productos para la venta',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 401,
              requerimentCode: 1,
              procedureDescription:
                'Existen productos de venta en uso en el Back office/ trastienda',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 402,
              requerimentCode: 2,
              procedureDescription:
                'Verificar que las bodegas se encuentran ordenadas y los productos bien almacenados',
              riskLevel: 'Medio',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 5,
          taskCode: 'E',
          procedureDescription: 'Seguimiento Visita Anterior',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 501,
              requerimentCode: 1,
              procedureDescription:
                'Cuando aplique, valide si se repiten las mismas observaciones que la auditoría anterior',
              riskLevel: 'Muy Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
      ]
    case 2: // Administracion - Replicar estructura similar
      return [
        // Tareas para el módulo de Administracion
        {
          id: 1,
          taskCode: 'A',
          procedureDescription: 'Fiscalizacion',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 101,
              requerimentCode: 1,
              procedureDescription:
                'Patente comercial se encuentra vigente y a la vista de los clientes',
              riskLevel: 'Muy Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 102,
              requerimentCode: 2,
              procedureDescription:
                'El Jefe de Tienda y Encargado de Zona sabe dónde se encuentra la declaración de IVA de los meses anteriores',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 2,
          taskCode: 'B',
          procedureDescription: 'Temas Varios',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'Los colaboradores conocen los procedimientos o instructivos que rigen la forma de operar de la tienda',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 202,
              requerimentCode: 2,
              procedureDescription:
                'El libro de sugerencias, Felicitaciones y reclamos cumple con las normas y requisitos establecidos',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 2,
          taskCode: 'C',
          procedureDescription: 'Seguimiento Visita Anterior',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'Cuando aplique, valide si se repiten las mismas observaciones que la auditoría anterior',
              riskLevel: 'Muy Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
      ]
    case 3: // TI Mantencion - Replicar estructura similar
      return [
        // Tareas para el módulo de TI Mantencion
        {
          id: 1,
          taskCode: 'A',
          procedureDescription: 'Mantencion',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 101,
              requerimentCode: 1,
              procedureDescription:
                '¿Se encuentran los centros eléctricos de las cajas en buen estado y anclados al mueble?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 102,
              requerimentCode: 2,
              procedureDescription: 'El piso y cobrejuntas se encuentran en buen estado?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 103,
              requerimentCode: 3,
              procedureDescription: '¿El techo se encuentra en buen estado?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 104,
              requerimentCode: 4,
              procedureDescription: 'Aire acondicionado se encuentra operativo y en buen estado',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 2,
          taskCode: 'B',
          procedureDescription: 'TI',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'La Sala Técnica/Electricidad se encuentra despejada (sin producto, cajas o artículo que no corresponda)',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 202,
              requerimentCode: 2,
              procedureDescription:
                'Se encuentra la UPS en el rack de comunicaciones funcionando y con los servidores conectados al mismo',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 203,
              requerimentCode: 3,
              procedureDescription:
                'Los Pinpad de contingencia están activos y con carga? Además ¿Se encuentran los cargadores de pinpad bien distribuidos para evitar alargadores?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 204,
              requerimentCode: 4,
              procedureDescription:
                '¿Los POS se encuentran todos operativos y en buen estado? Además ¿Se Encuentra el lineal de cajas bajo el POS despejado y sin artículos que puedan generar peligro a nivel eléctrico (Agua, papeles, alcohol, etc)?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 205,
              requerimentCode: 5,
              procedureDescription:
                'Tiene todos sus Tablets, impresoras, scanner, funcionando y en buen estado',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 3,
          taskCode: 'C',
          procedureDescription: 'Seguimiento Visita Anterior',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'Cuando aplique, valide si se repiten las mismas   observaciones que la auditoría anterior',
              riskLevel: 'Muy Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
      ]
    case 4: // RR.HH - SSO - Replicar estructura similar
      return [
        // Tareas para el módulo de RR.HH - SSO
        {
          id: 1,
          taskCode: 'A',
          procedureDescription: 'RR.HH',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 101,
              requerimentCode: 1,
              procedureDescription:
                'Los documentos de los colaboradores se encuentran firmados en Buk (Contrato, Reglamento Interno, Anexos, etc.)',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 102,
              requerimentCode: 2,
              procedureDescription:
                'Las Horas Extras se encuentran autorizadas por el Jefe Zonal a través de correo, además se cumple con la ley (máximo 2 HE diarias y 10 a la semana)',
              riskLevel: 'Muy Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 103,
              requerimentCode: 3,
              procedureDescription:
                'Jefaturas saben dónde se encuentra Registro de Firma Electrónica para presentar ante la inspección del trabajo',
              riskLevel: 'Medio',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 104,
              requerimentCode: 4,
              procedureDescription: '¿Las mallas de turno están firmadas y publicadas?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 2,
          taskCode: 'B',
          procedureDescription: 'SSO',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'Los extintores están en sus respectivos calzos y con su mantención al día?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 202,
              requerimentCode: 2,
              procedureDescription:
                'Las señaléticas de seguridad de la tienda están puestas y en buen estado? Además ¿Se encuentran las salidas(s) de emergencia libres para su uso?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 203,
              requerimentCode: 3,
              procedureDescription:
                'Se encuentra Registro Capacitación de uso y manejo de escaleras, Recepción de Camión y Uso de Cuchillo Cartonero',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 204,
              requerimentCode: 4,
              procedureDescription:
                'Si la tienda cuenta con más de 25 trabajadores, verificar que esté constituido el Comité Paritario, además que se encuentren las actas de reuniones mensuales firmadas',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 205,
              requerimentCode: 6,
              procedureDescription:
                'Verificar que se encuentre el registro de Control de Plagas que se realiza de forma mensual',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 3,
          taskCode: 'C',
          procedureDescription: 'Seguimiento Visita Anterior',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'Cuando aplique, valide si se repiten las mismas observaciones que la auditoría anterior',
              riskLevel: 'Muy Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
      ]
    case 5: // Recaudacion - Replicar estructura similar
      return [
        // Tareas para el módulo de Recaudacion
        {
          id: 1,
          taskCode: 'A',
          procedureDescription: 'Arqueo',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 101,
              requerimentCode: 1,
              procedureDescription:
                'Fondo de Sencillo cuadrado, ordenado y al interior de caja fuerte, en este ítem se debe abrir un recuadro en el cual se ingresa el desglose del fondo de sencillo asignado a la tienda',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 102,
              requerimentCode: 2,
              procedureDescription:
                'Tienda realiza cuadratura del Fondo de Sencillo todos los días',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 103,
              requerimentCode: 3,
              procedureDescription: 'Fondo de Sencillo del mes anterior depositado',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 2,
          taskCode: 'B',
          procedureDescription: 'Folios',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'Los retiros y depósitos en Compusafe cumplen con lo estipulado en el Procedimiento de Procesos y Sistema de Caja',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 202,
              requerimentCode: 2,
              procedureDescription:
                'Notas de Pedido cumplen con el protocolo, además se ingresan diariamente las NC por egreso en el drive',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 203,
              requerimentCode: 3,
              procedureDescription:
                'Se encuentra cuadrado el cierre de turno (no considerar voucher de débito y crédito)',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
            {
              id: 204,
              requerimentCode: 4,
              procedureDescription:
                '¿Las tarjetas de supervisor en tienda, se ajustan a protocolo vigente?',
              riskLevel: 'Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
        {
          id: 3,
          taskCode: 'C',
          procedureDescription: 'Seguimiento Visita Anterior',
          compliancePercentage: 0,
          taskRating: '',
          isCompleted: false,
          subtasks: [
            {
              id: 201,
              requerimentCode: 1,
              procedureDescription:
                'Cuando aplique, valide si se repiten las mismas observaciones que la auditoría anterior',
              riskLevel: 'Muy Alto',
              auditedSamples: 0,
              errorsFound: 0,
              errorPercentage: 0,
              compliancePercentage: 0,
              isCompleted: false,
              observations: [],
            },
          ],
        },
      ]
    default:
      return []
  }
}
